INSERT INTO TOY (ID, NAME, RECOMMENDED_AGE, PRICE) VALUES (1, 'Gun', 7,  10.00);
INSERT INTO TOY (ID, NAME, RECOMMENDED_AGE, PRICE) VALUES (2, 'Car', 3,  15.00);
INSERT INTO TOY (ID, NAME, RECOMMENDED_AGE, PRICE) VALUES (3, 'TeddyBear', 2,  36.00);
INSERT INTO TOY (ID, NAME, RECOMMENDED_AGE, PRICE) VALUES (4, 'Doll', 5,  43.00);